const questionsData = [
  {
    question: "What family do oranges and lemons belong to?",
    options: [
      'citrus',
      'solanum',
      'rubus',
      'rudbeckia',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "What is flax used for?",
    options: [
      'food',
      'making linel',
      'making rope',
      'poison',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "What is aloe vera used for?",
    options: [
      'topical medications',
      'food',
      'cosmetics',
      'making rope',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "What is the latin name for giant hogweed?",
    options: [
      'Heracleum sphondylium',
      'Heracleum mantegazzianum',
      'Fraxinus pennsylvanica',
      'Fraxinus quadrangulata',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'hard',
  },
  {
    question: "Which part of the cinnamon tree is used as a spice?",
    options: [
      'leaves',
      'bark',
      'roots',
      'flowers',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which of the following plants are carnivorous?",
    options: [
      'Venus flytrap',
      'pitcher plant',
      'sunflower',
      'sundew',
    ],
    answer: [0,1,3],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant is known for its high protein content and is often used in vegan diets?",
    options: [
      'soybean',
      'spinach',
      'broccoli',
      'quinoa',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "What is the main use of the plant 'Papaver somniferum'?",
    options: [
      'fiber',
      'spice',
      'medicine',
      'perfume',
    ],
    answer: 2,
    type: 'choice',
    difficulty: 'hard',
  },
  {
    question: "Which of these plants are succulents?",
    options: [
      'Aloe vera',
      'cactus',
      'orchid',
      'jade plant',
    ],
    answer: [0,1,3],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant is often associated with repelling mosquitoes?",
    options: [
      'basil',
      'lavender',
      'citronella',
      'daisy',
    ],
    answer: 2,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which of these are nitrogen-fixing plants?",
    options: [
      'pea',
      'bean',
      'wheat',
      'clover',
    ],
    answer: [0,1,3],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which vitamin is especially abundant in carrots?",
    options: [
      'Vitamin C',
      'Vitamin A',
      'Vitamin D',
      'Vitamin K',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which tree produces acorns?",
    options: [
      'oak',
      'maple',
      'birch',
      'elm',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which of the following are members of the nightshade family (Solanaceae)?",
    options: [
      'potato',
      'tomato',
      'bell pepper',
      'carrot',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which part of the plant conducts photosynthesis?",
    options: [
      'roots',
      'leaves',
      'flowers',
      'stems',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "What pigment in plants is responsible for their green color?",
    options: [
      'melanin',
      'chlorophyll',
      'carotene',
      'anthocyanin',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which of these trees is deciduous?",
    options: [
      'pine',
      'oak',
      'spruce',
      'fir',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which plants are used to make natural dyes?",
    options: [
      'indigo',
      'madder',
      'turmeric',
      'dandelion',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which of these are considered invasive species in many regions?",
    options: [
      'kudzu',
      'Japanese knotweed',
      'dandelion',
      'English ivy',
    ],
    answer: [0,1,3],
    type: 'multi-choice',
    difficulty: 'hard',
  },
  {
    question: "Which plant has psychoactive properties and is used in religious rituals by some cultures?",
    options: [
      'sage',
      'peyote',
      'lotus',
      'lavender',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'hard',
  },
  {
    question: "Which part of the peanut plant grows underground?",
    options: [
      'flower',
      'fruit (peanut)',
      'stem',
      'leaves',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant is known for its high caffeine content?",
    options: [
      'cocoa',
      'coffee',
      'guarana',
      'chamomile',
    ],
    answer: [1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "What do legumes add to the soil?",
    options: [
      'phosphorus',
      'calcium',
      'nitrogen',
      'potassium',
    ],
    answer: 2,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which of these fruits grow on trees?",
    options: [
      'banana',
      'apple',
      'mango',
      'grape',
    ],
    answer: [1,2],
    type: 'multi-choice',
    difficulty: 'easy',
  },
  {
    question: "Which plant is considered sacred in India?",
    options: [
      'neem',
      'lotus',
      'banyan',
      'tulsi (holy basil)',
    ],
    answer: [1,3],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "What is the botanical term for a plant that lives for more than two years?",
    options: [
      'annual',
      'biennial',
      'perennial',
      'ephemeral',
    ],
    answer: 2,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which of the following plants are gymnosperms?",
    options: [
      'pine',
      'fir',
      'oak',
      'ginkgo',
    ],
    answer: [0,1,3],
    type: 'multi-choice',
    difficulty: 'hard',
  },
  {
    question: "Which plant is known for closing its leaves when touched?",
    options: [
      'venus flytrap',
      'sensitive plant (Mimosa pudica)',
      'fern',
      'orchid',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which parts of the tomato plant are toxic?",
    options: [
      'fruit',
      'leaves',
      'stem',
      'roots',
    ],
    answer: [1,2],
    type: 'multi-choice',
    difficulty: 'hard',
  },
  {
    question: "Which of the following are parasitic plants?",
    options: [
      'mistletoe',
      'dodder',
      'orchid',
      'rafflesia',
    ],
    answer: [0,1,3],
    type: 'multi-choice',
    difficulty: 'hard',
  },
  {
    question: "Which plant is traditionally used to make paper?",
    options: [
      'papyrus',
      'hemp',
      'bamboo',
      'flax',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which fruit has seeds on the outside?",
    options: [
      'banana',
      'apple',
      'strawberry',
      'grape',
    ],
    answer: 2,
    type: 'choice',
    difficulty: 'easy',
  },
  {
    question: "Which trees are known for producing syrup?",
    options: [
      'oak',
      'birch',
      'maple',
      'cherry',
    ],
    answer: [1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant family includes broccoli, cabbage, and kale?",
    options: [
      'solanaceae',
      'brassicaceae',
      'fabaceae',
      'rosaceae',
    ],
    answer: 1,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant is the source of natural rubber?",
    options: [
      'Hevea brasiliensis',
      'Ficus elastica',
      'Aloe vera',
      'Eucalyptus globulus',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'hard',
  },
  {
    question: "Which of these plants are monocots?",
    options: [
      'corn',
      'wheat',
      'rice',
      'sunflower',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant is traditionally used in the production of tequila?",
    options: [
      'agave',
      'cactus',
      'sugarcane',
      'yucca',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which plants are often used in herbal teas?",
    options: [
      'chamomile',
      'mint',
      'hibiscus',
      'ivy',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'easy',
  },
  {
    question: "Which of these plants are commonly used as spices?",
    options: [
      'cinnamon',
      'clove',
      'nutmeg',
      'oregano',
    ],
    answer: [0,1,2,3],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "Which plant has the largest flower in the world?",
    options: [
      'rafflesia',
      'lotus',
      'sunflower',
      'titan arum',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'hard',
  },
  {
    question: "Which of these are aquatic plants?",
    options: [
      'lotus',
      'water lily',
      'duckweed',
      'fern',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
  {
    question: "What is the function of plant roots?",
    options: [
      'photosynthesis',
      'water absorption',
      'nutrient uptake',
      'seed dispersal',
    ],
    answer: [1,2],
    type: 'multi-choice',
    difficulty: 'easy',
  },
  {
    question: "Which plant is used to make aspirin originally?",
    options: [
      'willow',
      'poplar',
      'birch',
      'eucalyptus',
    ],
    answer: 0,
    type: 'choice',
    difficulty: 'medium',
  },
  {
    question: "Which of these plants are examples of legumes?",
    options: [
      'lentil',
      'chickpea',
      'soybean',
      'spinach',
    ],
    answer: [0,1,2],
    type: 'multi-choice',
    difficulty: 'medium',
  },
];

